# Generated by Django 4.1.7 on 2026-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discogs_id", models.CharField(blank=True, max_length=20)),
                ("barcode", models.CharField(blank=True, max_length=30)),
                ("catalog_number", models.CharField(blank=True, max_length=50)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("Vinyl", "Vinyl"),
                            ("CD", "CD"),
                            ("Cassette", "Cassette"),
                            ("Other", "Other"),
                        ],
                        default="Vinyl",
                        max_length=20,
                    ),
                ),
                ("format_details", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=2100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("listed", "Listed"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("record_available", models.BooleanField(default=True)),
            ],
        ),
    ]
