# Generated by Django 4.1.7 on 2026-09-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="condition_photo",
            field=models.ImageField(
                blank=True,
                help_text="A real photo of this specific copy (optional). Resized automatically on save.",
                null=True,
                upload_to="record_photos/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="media_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mint", "Mint (M)"),
                    ("near_mint", "Near Mint (NM)"),
                    ("vg_plus", "Very Good Plus (VG+)"),
                    ("very_good", "Very Good (VG)"),
                    ("good_plus", "Good Plus (G+)"),
                    ("good", "Good (G)"),
                    ("fair", "Fair (F)"),
                    ("poor", "Poor (P)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="sleeve_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mint", "Mint (M)"),
                    ("near_mint", "Near Mint (NM)"),
                    ("vg_plus", "Very Good Plus (VG+)"),
                    ("very_good", "Very Good (VG)"),
                    ("good_plus", "Good Plus (G+)"),
                    ("good", "Good (G)"),
                    ("fair", "Fair (F)"),
                    ("poor", "Poor (P)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecordInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="music.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
