# Generated by Django 4.2.30 on 2026-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('listed', 'Listed'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_available',
            field=models.BooleanField(default=True),
        ),
    ]
