# Generated by Django 4.1.7 on 2026-09-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_quantity_book_status_alter_book_book_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("like_new", "Like New"),
                    ("very_good", "Very Good"),
                    ("good", "Good"),
                    ("acceptable", "Acceptable / Well-worn"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="condition_photo",
            field=models.ImageField(
                blank=True,
                help_text="A real photo of this specific copy (optional). Resized automatically on save.",
                null=True,
                upload_to="book_photos/%Y/%m/",
            ),
        ),
        migrations.CreateModel(
            name="BookInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
